# Generated by Django 3.0.3 on 2020-02-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('registration', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('user_img', models.ImageField(upload_to='users/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id_rev', models.AutoField(primary_key=True, serialize=False)),
                ('reviews', models.TextField(max_length=1000, verbose_name='Комментарий')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painting.Users')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painting.Users')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
