# Generated by Django 3.0.3 on 2020-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
