# Generated by Django 3.0.3 on 2020-02-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_auto_20200209_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='id_user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
