# Generated by Django 3.0.3 on 2020-04-08 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0004_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pictures',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
